### ISSUE TITLE
LogicError: No additional properties in type

### ISSUE THREAD

**Issue by muzea** [vega/ts-json-schema-generator#136]
Step to reproduce:

```shell
yarn global add ts-json-schema-generator
yarn global add antd@3.19.6
cd `yarn global dir`/node_modules/antd
ts-json-schema-generator --path es/form/index.d.ts --type 'Form' --expose 'none' --jsDoc 'none' --no-type-check --no-top-ref
```

Will receive an error

```
LogicError: No additional properties in type "["horizontal","inline","vertical"]"
```

**Comment by kayahr** [comment]
You are trying to create a JSON schema for a class which is extending React.Component. Are you sure that's what you want to do? What sense does it make to have a JSON schema for such a type?

Anyway, the extracted problematic code is actually this:

```typescript
declare const FormLayouts: ["horizontal", "inline", "vertical"];
export declare type FormLayout = (typeof FormLayouts)[number];
```

Generating the schema for type `FormLayout` fails.

**Comment by kayahr** [comment]
PR #139 will fix this problem. 

But even with this you will not be able to create a JSON schema for this complex Form class. The next problematic part will be this interesting type:

```
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
```

So this is actually a function type and functions are not supported in JSON and therefor out-of-scope for a JSON schema generator.

**Comment by muzea** [comment]
@kayahr 
Last week, I was trying to use type information to determine which version of an api was added. Want to provide a script that can automatically modify the documentation for [Update website APIs to show version Number features were added](https://github.com/ant-design/ant-design/issues/17054).

**Comment by 545682879** [comment]
when I run  
```
yarn global add ts-json-schema-generator
yarn global add antd@3.19.6
cd `yarn global dir`/node_modules/antd
ts-json-schema-generator --path es/form/index.d.ts --type 'Form' --expose 'none' --jsDoc 'none' --no-type-check --no-top-ref
```

it raise error:

```
  at Object.isEnumDeclaration (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/node_modules/typescript/lib/typescript.js:11757:21)
    at TypeofNodeParser.createType (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeofNodeParser.js:23:16)
    at ChainNodeParser.createType (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at /Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/NodeParser/IntersectionNodeParser.js:17:72
    at Array.map (<anonymous>)
    at IntersectionNodeParser.createType (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/NodeParser/IntersectionNodeParser.js:17:34)
    at ChainNodeParser.createType (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at /Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/NodeParser/InterfaceAndClassNodeParser.js:95:106
    at Array.map (<anonymous>)
    at InterfaceAndClassNodeParser.getProperties (/Users/vivichen/.config/yarn/global/node_modules/ts-json-schema-generator/dist/src/NodeParser/InterfaceAndClassNodeParser.js:95:14)
```

do you know why? thanks
