### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by tommedema** [vega/ts-json-schema-generator#1727]
When following your instructions on how to add a formatter for functions, this is the output I'm seeing:

```
> node scripts/reflect.mjs

/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:23
            this.typeCaches.set(node, typeCache);
                            ^

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at ChainNodeParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:23:29)
    at ParameterParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/NodeParser/ParameterParser.js:16:37)
    at AnnotatedNodeParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/NodeParser/AnnotatedNodeParser.js:30:47)
    at ChainNodeParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at /Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/NodeParser/FunctionParser.js:24:41
    at Array.map (<anonymous>)
    at FunctionParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/NodeParser/FunctionParser.js:23:48)
    at ChainNodeParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at TopRefNodeParser.createType (/Users/tommedema/Code/seai/seai-controller/node_modules/ts-json-schema-generator/dist/src/TopRefNodeParser.js:12:47)
```

Reflect.mjs looks like this:

```
import tsj, { SchemaGenerator, createParser, createProgram } from 'ts-json-schema-generator'
import fs from 'fs'
import { Project } from 'ts-morph'
import path from 'path'

import SimpleFunctionTypeFormatter from './reflect-function-formatter.mjs'

const CWD = process.cwd()
const NAMESPACES_DIR = `${CWD}/src/namespaces`
const SOURCE_PATH_GLOB = `${NAMESPACES_DIR}/**/*.ts`
const REFLECTION_DIR = `${CWD}/reflection`
const TSCONFIG_PATH = `${CWD}/tsconfig.json`

// Create a new project instance
const project = new Project()

// Add source files
const sourceFiles = project.addSourceFilesAtPaths(SOURCE_PATH_GLOB)

// Process each source file
for (const sourceFile of sourceFiles) {
  const filePath = sourceFile.getFilePath()

  const config = {
    path: filePath,
    tsconfig: TSCONFIG_PATH,
    expose: 'all',
    encodeRefs: false,
    topRef: true,
    type: '*'
  }

  // See https://github.com/vega/ts-json-schema-generator
  const formatter = tsj.createFormatter(config, (fmt, circularReferenceTypeFormatter) => {
    fmt.addTypeFormatter(new SimpleFunctionTypeFormatter())
  })
  const program = createProgram(config)
  const parser = createParser(program, config)
  const generator = new SchemaGenerator(program, parser, formatter, config)
  const schema = generator.createSchema(config.type)
  const schemaString = JSON.stringify(schema, null, 2)

  let outputPath = path.join(REFLECTION_DIR, path.relative(NAMESPACES_DIR, filePath))
  outputPath = path.format({ ...path.parse(outputPath), base: '', ext: '.json' })

  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFile(outputPath, schemaString, (err) => {
    if (err) {
      throw err
    }
  })
}
```

and reflect-function-formatter.mjs:

```
import tsj from 'ts-json-schema-generator'

class SimpleFunctionTypeFormatter {
  constructor (childTypeFormatter) {
    this.childTypeFormatter = childTypeFormatter
  }

  supportsType (type) {
    return type instanceof tsj.FunctionType
  }

  getDefinition (type) {
    return {
      type: 'object',
      properties: {
        isFunction: {
          type: 'boolean',
          const: true
        }
      }
    }
  }

  getChildren (type) {
    return []
  }
}

export default SimpleFunctionTypeFormatter
```

I'm on Typescript 5.1.6 and ts-json-schema-generator 1.3.0-next.7 and Node.js v20.3.0

**Comment by tommedema** [comment]
Alternatively, if it is possible to simply not return function definitions instead of throwing `UnknownTypeError: Unknown type "function""` that would also work for my use case

**Comment by tommedema** [comment]
This only occured on one file, I don't know why, but I suppose it is practical to just ignore it:

```
import { type Dispatch, type Middleware, isAction } from '@reduxjs/toolkit'
import objectPath from 'object-path'
import { type ReduxAction, type RootState, isReduxAction } from '../../../lib/types.js'
import viewNamespace from '../../__view/index.js'
import reduxNamespace from '../index.js'

const { setStatePathResult } = viewNamespace.actions
const { _broadcastAllSagasFulfilled } = reduxNamespace.actions

export const stateObjectPathMiddleware: Middleware<unknown, RootState, Dispatch<ReduxAction>> = (storeApi) => (next) => (action) => {
  const result = next(action)

  let state: RootState | null = null
  let statePath: string | null = null

  // Set statePath if we need to set the path result
  if (isReduxAction(action) && action.type !== setStatePathResult.type) {
    statePath = action.meta.selectStatePath
  } else if (isAction(action) && action.type === _broadcastAllSagasFulfilled.type) {
    // Update the path result to the latest once async work has completed
    state = storeApi.getState()
    statePath = state.__view.statePath
  }

  // Set the path result if statePath is set
  if (typeof statePath === 'string') {
    if (state == null) {
      state = storeApi.getState()
    }

    const pathResult = objectPath.get(state, statePath)

    storeApi.dispatch({
      ...setStatePathResult({ pathResult, statePath }),
      meta: {
        selectStatePath: null
      }
    })
  }

  return result
}
```
