### ISSUE TITLE
Generation failing for custom utility type

### ISSUE THREAD

**Issue by countnazgul** [vega/ts-json-schema-generator#1855]
For some reason generation is failing for the following:

```ts
type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U];

export interface SomeInterface {
    props: AtLeastOne<{
        prop1: string[];
        prop2: string[];
        prop3: string[];
    }>;
}
```

with the following error:

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'getId')
    at <anonymous> (C:\Dev\Temp\node_modules\ts-json-schema-generator\dist\src\Utils\nodeKey.js:43:57)
    at getKey (C:\Dev\Temp\node_modules\ts-json-schema-generator\dist\src\Utils\nodeKey.js:43:40)
    at getCacheKey (C:\Dev\Temp\node_modules\ts-json-schema-generator\dist\src\NodeParser.js:30:55)
    at createType (C:\Dev\Temp\node_modules\ts-json-schema-generator\dist\src\ChainNodeParser.js:25:41)
```

Have a look at the [codesandbox](https://codesandbox.io/p/devbox/flamboyant-shape-45t53v) example and [ts playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCMAywCGBnGAeQDtgAeAFQBo4BVOAXjgG84BtAaTgEti4BrYIggAzOBQC6ALjgAFbgGN+lGhwB8cAL4amsnLG44ANpQ0AyAFBw6bQcLG0JAbgsXQkWD2IxgUETgVUAGUIAFtgAElvX39Alis4MCgIMDwZDGx8IlIyZgTrJJSARhkCKF4AczZnfMTksAAmUphy4iqa6wL6gGZm1vaXa20XTVcjYHgIfhkQ8KifPwDUJjzOupS0+LW1wrAS9gla0dGLccn+fdnI6MW4ldrdzdXtruKZaqpanZ73w7XjsYTODECBEaZwK7zGJLRhbTqPGR5I4WTRAA)

**Comment by ELigoP** [comment]
I've got similar issue when using kind of `A<T, U = something depending on T>` and then referencing this as `A<SomeType>`. I hoped `U` will be inferred, but got this error instead. Had to go another way.

**Comment by arthurfiorette** [comment]
I got it working with this latest release:

```json
{
  "$ref": "#/definitions/SomeInterface",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "SomeInterface": {
      "additionalProperties": false,
      "properties": {
        "props": {
          "anyOf": [
            {
              "additionalProperties": false,
              "properties": {
                "prop1": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop2": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop3": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "prop1"
              ],
              "type": "object"
            },
            {
              "additionalProperties": false,
              "properties": {
                "prop1": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop2": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop3": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "prop2"
              ],
              "type": "object"
            },
            {
              "additionalProperties": false,
              "properties": {
                "prop1": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop2": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prop3": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "prop3"
              ],
              "type": "object"
            }
          ]
        }
      },
      "required": [
        "props"
      ],
      "type": "object"
    }
  }
}
```
