### ISSUE TITLE
Bug: `ReferenceError: structuredClone is not defined`

### ISSUE THREAD

**Issue by Wassap124** [vega/ts-json-schema-generator#1911]
Hey :)

Trying to upgrade to the new `1.5.1` version.
but getting this error:

```
/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:99
        throw error;
        ^

ReferenceError: structuredClone is not defined
    at deepMerge (/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/Utils/deepMerge.js:6:20)
    at /Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/Utils/allOfDefinition.js:10:59
    at Array.reduce (<anonymous>)
    at ObjectTypeFormatter.getDefinition (/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/ObjectTypeFormatter.js:28:22)
    at ChainTypeFormatter.getDefinition (/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:17:44)
    at CircularReferenceTypeFormatter.getDefinition (/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/CircularReferenceTypeFormatter.js:20:59)
    at /Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/SchemaGenerator.js:97:56
    at Array.reduce (<anonymous>)
    at SchemaGenerator.appendRootChildDefinitions (/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/SchemaGenerator.js:94:18)
    at /Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/src/SchemaGenerator.js:32:46
/Users/alonkazimirsky/myRepo/services/deployment-service
/Users/alonkazimirsky/myRepo/services/blueprint-service
/Users/alonkazimirsky/myRepo/node_modules/.pnpm/ts-json-schema-generator@1.5.1/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:99
```

i have this script in my `package.json`
```
"schema:generate": "find . -name \"schema.d.ts\" \\(  -path \"*/*-service/*\" -o -path \"*/common/*\"  \\) -execdir bash -c \"pwd && npx ts-json-schema-generator -p schema.d.ts -o schema.json -f tsconfig.json --no-ref-encode\" \\;",
```

im using `pnpm@7.33.4`

i see that one of the bug fixes in the release is 
> - fix(deepMerge): deepMerge is altering parameter definitions https://github.com/vega/ts-json-schema-generator/pull/1888 ([@chatelgu](https://github.com/chatelgu))

i guess it's related to that 

in the previous `1.5.0` everything works fine

**Comment by domoritz** [comment]
It's available in node 17. Which version are you using?

**Comment by Wassap124** [comment]
v16.15.0 😅

**Comment by domoritz** [comment]
Node 16 is way past end of life so you should update. 

https://nodejs.org/en/about/previous-releases

**Comment by Wassap124** [comment]
ok it works now, but there's a different problem - ill ask about it in a separate issue 🙏
