### ISSUE TITLE
`--expose all` breaks generation with generic types.

### ISSUE THREAD

**Issue by kelleyk** [vega/ts-json-schema-generator#2002]
I'm using the latest release (v2.3.0) of `ts-json-schema-generator`.

While trying to get it running on my project, I ran into the following somewhat opaque error:

```
/path/to/project/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:74
    throw error;
    ^

TypeError: Cannot read properties of undefined (reading 'getId')
    at new UnknownTypeError (/path/to/project/node_modules/ts-json-schema-generator/dist/src/Error/Errors.js:24:48)
    at ChainTypeFormatter.getTypeFormatter (/path/to/project/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:29:15)
    at ChainTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:21:21)
    at CircularReferenceTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/CircularReferenceTypeFormatter.js:30:50)
    at /path/to/project/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/ObjectTypeFormatter.js:43:59
    at Array.reduce (<anonymous>)
    at ObjectTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/ObjectTypeFormatter.js:38:44)
    at ChainTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:21:44)
    at CircularReferenceTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/CircularReferenceTypeFormatter.js:30:50)
    at DefinitionTypeFormatter.getChildren (/path/to/project/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/DefinitionTypeFormatter.js:21:84)
```

Using the [`generic-simple`](https://github.com/vega/ts-json-schema-generator/blob/next/test/valid-data/generic-simple/main.ts) test input, I think that I've narrowed down the things that trigger the error.  In particular, the generator runs without error when the input does not contain generic TypeScript types and the `--expose all` command-line parameter is present, or vice versa; but that error is thrown when both are present.

I couldn't find any other issues that seem similar.

**Comment by arthurfiorette** [comment]
Hey @kelleyk, could you create a minimum reproducible example so that we can debug?

**Comment by kelleyk** [comment]
Sure; sorry if I wasn't clear enough: I think that the `generic-simple` test input that is in this repository is a pretty decent "minimal repro".

It contains the following TypeScript type definintions:
```
export interface MyGeneric<T> {
    field: T;
}

export interface MyObject {
    value: MyGeneric<number>;
}
```

This, without `--expose all`, works fine.

```
$ npx ts-json-schema-generator --path ~/src/github.com/vega/ts-json-schema-generator/test/valid-data/generic-simple/main.ts --out /tmp/foo.json
```

When I add `--expose all`, however, I get the error that I mentioned above.
```
$ npx ts-json-schema-generator --path ~/src/github.com/vega/ts-json-schema-generator/test/valid-data/generic-simple/main.ts --out /tmp/foo.json --expose all
/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:74
    throw error;
    ^

TypeError: Cannot read properties of undefined (reading 'getId')
    at new UnknownTypeError (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/Error/Errors.js:24:48)
    at ChainTypeFormatter.getTypeFormatter (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:29:15)
    at ChainTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:21:21)
    at CircularReferenceTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/CircularReferenceTypeFormatter.js:30:50)
    at /Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/ObjectTypeFormatter.js:43:59
    at Array.reduce (<anonymous>)
    at ObjectTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/ObjectTypeFormatter.js:38:44)
    at ChainTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/ChainTypeFormatter.js:21:44)
    at CircularReferenceTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/CircularReferenceTypeFormatter.js:30:50)
    at DefinitionTypeFormatter.getChildren (/Users/kelleyk/.npm/_npx/dec19a6f9609cbed/node_modules/ts-json-schema-generator/dist/src/TypeFormatter/DefinitionTypeFormatter.js:21:84)
```

Let me know if there's anything else you need!

**Comment by arthurfiorette** [comment]
hey @kelleyk can you try with `@2.3.1--canary.2009.14b4e3c.0` and see if it was fixed?
