### ISSUE TITLE
error generating schema for keyof typeof x

### ISSUE THREAD

**Issue by mdesousa** [vega/ts-json-schema-generator#2034]
if you try to generate a schema for `MyKey` you get an error: "Invalid value used as weak map ke"

```
const myprop = 0;
export const mymap = { myprop };
export type MyKey = keyof typeof mymap;
```

see stack trace below, this is version 2.3.0. thanks!

```
Error processing ./test.ts: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at ChainNodeParser.createType (/node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:30:29)
    at <anonymous> (/node_modules/ts-json-schema-generator/src/NodeParser/ObjectLiteralExpressionNodeParser.ts:21:42)
    at Array.map (<anonymous>)
    at ObjectLiteralExpressionNodeParser.createType (/node_modules/ts-json-schema-generator/src/NodeParser/ObjectLiteralExpressionNodeParser.ts:17:44)
    at ChainNodeParser.createType (/node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:35:45)
    at TypeofNodeParser.createType (/node_modules/ts-json-schema-generator/src/NodeParser/TypeofNodeParser.ts:54:45)
    at ChainNodeParser.createType (/node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:35:45)
    at TypeOperatorNodeParser.createType (/node_modules/ts-json-schema-generator/src/NodeParser/TypeOperatorNodeParser.ts:21:43)
    at ChainNodeParser.createType (/node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:35:45)
```

**Comment by mdesousa** [comment]
hi @arthurfiorette tried this out with `v2.4.0-next.3` but it's throwing a new error now. please let me know if i can shared any additional data to help troubleshoot... thanks.

```
Error processing ./mycode.ts: TypeError: Cannot read properties of undefined (reading 'getId')
    at isAssignableTo (/.../node_modules/ts-json-schema-generator/src/Utils/isAssignableTo.ts:125:16)
    at <anonymous> (/.../node_modules/ts-json-schema-generator/src/NodeParser/ConditionalTypeNodeParser.ts:44:77)
    at narrowType (/.../node_modules/ts-json-schema-generator/src/Utils/narrowType.ts:59:12)
    at ConditionalTypeNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/NodeParser/ConditionalTypeNodeParser.ts:44:41)
    at ChainNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:35:45)
    at TypeAliasNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/NodeParser/TypeAliasNodeParser.ts:40:43)
    at AnnotatedNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/NodeParser/AnnotatedNodeParser.ts:34:47)
    at ExposeNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/ExposeNodeParser.ts:23:45)
    at CircularReferenceNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/CircularReferenceNodeParser.ts:24:43)
    at ChainNodeParser.createType (/.../node_modules/ts-json-schema-generator/src/ChainNodeParser.ts:35:45)
```

**Comment by arthurfiorette** [comment]
I'm afraid this error is not happening with the example above. What is the code you are trying to generate?

**Comment by mdesousa** [comment]
just tried and you are right, the keyof issue is fixed. this seems unrelated... i'll look deeper and file a new issue if needed.
thanks again @arthurfiorette
