### ISSUE TITLE
"TypeError: Cannot read property 'reduce' of undefined" in MappedTypeNodeParser.getProperties

### ISSUE THREAD

**Issue by MarcusRiemer** [vega/ts-json-schema-generator#38]
I am scratching my head about this crash for more then a few minutes now. Unfortunately I have no idea how to resolve this, but I have at least a source file that triggers the problem. The crash seems to be related to a rather complicated type I have:

```
// Resolves a value at runtime. The value must be the name of a parameter
// that has been formally introduced before.
export interface ParameterReference {
  "$ref": string
}

// Allows properties of an object to be optional and to be
// a reference that can be resolved to an actual value later.
export type ParameterReferenceable<T> = {
  [P in keyof T]?: T[P] | ParameterReference;
}

// Type can be generated without problems
export interface TestInterface {
  myStr: string;
  myNum: number;
}

// Crashes with stacktrace below
export type RefTestInterface = ParameterReferenceable<TestInterface>;
```

I attempted to generate the schemas as follows, the second call ends in the mentioned stacktrace.
```
./node_modules/.bin/ts-json-schema-generator --path ./repro.ts --type TestInterface
./node_modules/.bin/ts-json-schema-generator --path ./repro.ts --type RefTestInterface
```

The exact stacktrace reads like this and seems to be in the function ` MappedTypeNodeParser.getProperties`:

```
TypeError: Cannot read property 'reduce' of undefined
    at MappedTypeNodeParser.getProperties (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/NodeParser/MappedTypeNodeParser.js:19:14)
    at MappedTypeNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/NodeParser/MappedTypeNodeParser.js:14:92)
    at ChainNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:17:50)
    at TypeAliasNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeAliasNodeParser.js:20:94)
    at AnnotatedNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/NodeParser/AnnotatedNodeParser.js:15:47)
    at ExposeNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/ExposeNodeParser.js:14:45)
    at CircularReferenceNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/CircularReferenceNodeParser.js:19:48)
    at ChainNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:17:50)
    at TypeReferenceNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeReferenceNodeParser.js:22:41)
    at ChainNodeParser.createType (/home/marcus/projects/scratch-sql/schema/json/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:17:50)
```

My versions:
```
> node --version                                                                                                                                                      
v10.7.0
> grep "ts-json-schema-generator" package-lock.json                                                                                                                    
      "resolved": "https://registry.npmjs.org/ts-json-schema-generator/-/ts-json-schema-generator-0.29.0.tgz",
```

**Comment by domoritz** [comment]
You can try to step through the code. I have a script endpoint where you can add breakpoints and look at the variables at the point of the error.

**Comment by MarcusRiemer** [comment]
I will see whether I can dig something up that way. But it seems that I am at least not stumbling over a known limitation?

**Comment by domoritz** [comment]
Mapped types are tricky and we recently added some more support for it but it's certainly not complete.

**Comment by MarcusRiemer** [comment]
Huh, interestingly the current state in `master` does not crash.  So apparently [something in this changeset has fixed the problem](https://github.com/vega/ts-json-schema-generator/compare/v0.29.0...master).

And from the looks of it the resulting schema is perfectly fine:
```
{
  "$ref": "#/definitions/RefTestInterface",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "ParameterReference": {
      "additionalProperties": false,
      "properties": {
        "$ref": {
          "type": "string"
        }
      },
      "required": [
        "$ref"
      ],
      "type": "object"
    },
    "ParameterReferenceable<TestInterface>": {
      "additionalProperties": false,
      "properties": {
        "myNum": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/ParameterReference"
            }
          ]
        },
        "myStr": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/definitions/ParameterReference"
            }
          ]
        }
      },
      "type": "object"
    },
    "RefTestInterface": {
      "$ref": "#/definitions/ParameterReferenceable<TestInterface>"
    }
  }
}
```

Would you be interested in a PR with this exact testcase?

**Comment by MarcusRiemer** [comment]
Oh, and I would really appreciate a version bump with the current `master`. Would you be able to do this in a timely manner? In that case I wouldn't have to roll out a `package.json` with a `git`-package.

**Comment by MarcusRiemer** [comment]
Sorry for making such a series of live updates here, I am literally letting you know what happens as I discover it. Right now I had at least two validators stumble over `"#/definitions/ParameterReferenceable<TestInterface>"` because `<` and `>` are not allowed to appear unescaped in an URL. So these would require escaping.

**Comment by domoritz** [comment]
Oh, I didn't know it wasn't released. I'll do that soon.

**Comment by domoritz** [comment]
Done in 0.30
