### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by nightInSummer** [vega/ts-json-schema-generator#471]
When I try to tanslate this d.ts
```js
import Vue from 'vue'

export declare class VXETableModule extends Vue {
  /**
   * 
   * @default 'default'
   * @type string
   */
  size?: 'medium' | 'small' | 'mini';

  static install(vue: typeof Vue): void;
}
```
I get this error message
```js
TypeError: Cannot read property 'kind' of undefined
    at Object.isEnumDeclaration (/Users/mac/work/ts-json-schema-generator/node_modules/typescript/lib/typescript.js:11760:21)
    at TypeofNodeParser.createType (/Users/mac/work/ts-json-schema-generator/dist/src/NodeParser/TypeofNodeParser.js:23:16)
    at ChainNodeParser.createType (/Users/mac/work/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at /Users/mac/work/ts-json-schema-generator/dist/src/NodeParser/IntersectionNodeParser.js:21:72
    at Array.map (<anonymous>)
    at IntersectionNodeParser.createType (/Users/mac/work/ts-json-schema-generator/dist/src/NodeParser/IntersectionNodeParser.js:21:34)
    at ChainNodeParser.createType (/Users/mac/work/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at AnnotatedNodeParser.createType (/Users/mac/work/ts-json-schema-generator/dist/src/NodeParser/AnnotatedNodeParser.js:19:47)
    at /Users/mac/work/ts-json-schema-generator/dist/src/NodeParser/InterfaceAndClassNodeParser.js:95:106
    at Array.map (<anonymous>)
```

**Comment by domoritz** [comment]
Can you simplify the example to not use vue?

**Comment by nightInSummer** [comment]
@domoritz I only get this error when I use vue

**Comment by domoritz** [comment]
Closing as a minimal test case is required.

**Comment by thw0rted** [comment]
I think my issue #1016 is a minimal reproduction (without Vue), it dumps roughly the same stack trace.
