### ISSUE TITLE
Incompatible with io-ts?

### ISSUE THREAD

**Issue by mooyoul** [vega/ts-json-schema-generator#507]
Hello there, I'm trying to use ts-json-schema-generator with io-ts, but currently it doesn't work well.

##### Work as expected

`string.ts`

```typescript
import * as t from "io-ts";
type MyType = t.TypeOf<typeof t.string>;

export class MyClass {
  public constructor(public type: MyType) {};
}
```

```bash
$ node_modules/.bin/ts-json-schema-generator -p string.ts
```

##### Broken

`string-broken.ts`

```typescript
import * as t from "io-ts";

const MyTypeT = t.string;
type MyType = t.TypeOf<typeof MyTypeT>;

export class MyClass {
  public constructor(public type: MyType) {};
}
```

```bash
$ node_modules/.bin/ts-json-schema-generator -p string-broken.ts
```

results to

```
Error: Unknown node "MyType" (ts.SyntaxKind = 198) at /Users/Prescott/Documents/Workspace/scratch/string-broken.ts(7,34)
```

### Object Type

`object.ts`

```typescript
import * as t from "io-ts";

const MyTypeT = t.type({ foo: t.string });
type MyType = t.TypeOf<typeof MyTypeT>;

export class MyClass {
  public constructor(public type: MyType) {};
}
```

```bash
$ node_modules/.bin/ts-json-schema-generator -p object.ts
```

results to

```
/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:45
        throw error;
        ^

TypeError: Cannot read property 'map' of undefined
    at CallExpressionParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/CallExpressionParser.js:19:67)
    at ChainNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at TypeofNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeofNodeParser.js:31:45)
    at ChainNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at TypeReferenceNodeParser.createSubContext (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeReferenceNodeParser.js:51:51)
    at TypeReferenceNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeReferenceNodeParser.js:44:121)
    at ChainNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/ChainNodeParser.js:28:54)
    at TypeAliasNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/TypeAliasNodeParser.js:33:43)
    at AnnotatedNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/NodeParser/AnnotatedNodeParser.js:19:47)
    at ExposeNodeParser.createType (/Users/Prescott/Documents/Workspace/scratch/node_modules/ts-json-schema-generator/dist/src/ExposeNodeParser.js:17:45)
```

please let me know If you need further assistance :)

**Comment by domoritz** [comment]
It looks like you are hitting an edge case. Please reduce the issue to only your code and no imports.

**Comment by mooyoul** [comment]
Okay, Here's another reproducible code which dropped io-ts usage:

```typescript
type TypeOf<T extends Codec<any>> = T["type"];

class Codec<T> {
  type: T;
}

const StringType = new Codec<string>();
type MyType = TypeOf<typeof StringType>;

export class MyClass {
  public constructor(public type: MyType) {}
}
```

**Comment by domoritz** [comment]
Awesome! Can you try to reduce the example even further?
