### ISSUE TITLE
Error: Unknown type "function"

### ISSUE THREAD

**Issue by treenwang** [vega/ts-json-schema-generator#560]
When parsing a typescript file like this:
```
 export type FunctionType = () => string 
```
or
```
export type FunctionType = {
    testFunction: () => string
};
```
An error will be throws:
``` 
Error: Unknown type "function"
    at ChainTypeFormatter.getTypeFormatter (/Users/treenwang/Work/product/graphql-service/node_modules/ts-json-schema-generator/dist/src/src/src/ChainTypeFormatter.ts:31:15)
    at ChainTypeFormatter.getChildren (/Users/treenwang/Work/product/graphql-service/node_modules/ts-json-schema-generator/dist/src/src/src/ChainTypeFormatter.ts:21:21)
```

**Comment by domoritz** [comment]
Json schema has no support for functions. I'm happy to review a pull request that makes the parser just ignore them with a warning instead of crash.

**Comment by broofa** [comment]
Breadcrumbs for people searching this error message:
* https://github.com/vega/ts-json-schema-generator/issues/104#issuecomment-569844178
* #1182
